### PR TITLE
Learning - using crops for selecting training regions

### PR DESCRIPTION
**Pull request by ilastikdev**
Required for crop selection and training applets in the new Structured Learning Tracking workflow.

### CODE REVIEW

**Comment by stuarteberg** [comment]
As far as I can tell, the class you are attempting to merge here is just a copy of the existing `OpCompressedUserLabelArray` class, with the exception of some slot/variable name changes.  Is there a difference I'm missing?

If not, I think it would be better to delete this class and just use the existing one.  If there is some subtle difference that I didn't notice, then the operator should be implemented in such a way that avoids code duplication with the original.

**Comment by ilastikdev** [comment]
ilastik/lazyflow learning is ready to be pulled into 
ilastik/lazyflow master

**Comment by stuarteberg** [comment]
Your most recent commits effectively revert the previous changes in this branch, leaving this PR empty.  (That's why github's "Files changed" view above has 0 files listed.)

Instead of merging a string of commits that do nothing in the end, is it okay to just close this PR without merging it?

**Comment by ilastikdev** [comment]
of course

**Pull request closed without merging**
