### PR TITLE
Integrated Sven's fast filters

### PR DESCRIPTION
**Pull request by JaimeIvanCervantes**
Integrated @svenpeter42 fast filters into Ilastik. Some points worth noting:

* Sven's filters are only supported on Linux and Mac.
* The code includes wrappers for each filter that check for contiguous arrays, and make sure that vigra arrays are being passed.
* `OpPixelFeaturesPresmoothed` includes a slot to enable/disable the fast filters in case that we need to do this manually for debugging purposes.

### CODE REVIEW

**Comment by stuarteberg** [comment]
>`OpPixelFeaturesPresmoothed` includes a slot to enable/disable the fast filters

I would prefer not to add a slot to this operator.  It adds API surface area, whereas the variable `WITH_FAST_FILTERS` is just as good for debugging purposes.

**Comment by JaimeIvanCervantes** [comment]
@svenpeter42 You mentioned that you are already checking for contiguous arrays on your code, should I do this from within Ilastik too? Or is it redundant?

**Comment by stuarteberg** [comment]
Can you fix the commit message on f1c9eb7 (`git commit --amend`) and re-push (`git push -f`)?

**Comment by JaimeIvanCervantes** [comment]
Ups! Sorry for the typo, I don't know what I was thinking. Tuesday morning.

**Comment by svenpeter42** [comment]
no need to check for continuous arrays here - it's done three times at this point :-)
(once in ilastik, once in __init__.py and then again in pybind)

**Comment by svenpeter42** [comment]
looks like something's broken in the fastfilters detection code - this happens when i start ilastik inside a conda environment with no fastfilters installed:
```

% ./run_ilastik.sh 
Warning: Ignoring your non-empty QT_PLUGIN_PATH
Starting ilastik from "/home/speter/miniconda2/envs/ilastik-ff-test".
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/excepthooks.py", line 53, in display_and_log
    from volumina.pixelpipeline.asyncabcs import IndeterminateRequestError
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/__init__.py", line 42, in <module>
    import api
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/api.py", line 29, in <module>
    from volumina.widgets.layerwidget import LayerWidget
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/widgets/layerwidget.py", line 31, in <module>
    from layercontextmenu import layercontextmenu
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/widgets/layercontextmenu.py", line 32, in <module>
    from exportHelper import get_settings_and_export_layer
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/widgets/exportHelper.py", line 44, in <module>
    from lazyflow.graph import Graph
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/__init__.py", line 32, in <module>
    import operators
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/operators/__init__.py", line 32, in <module>
    from vigraOperators import Op1ToMulti, Op5ToMulti, Op50ToMulti
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/operators/vigraOperators.py", line 1518, in <module>
    class OpGaussianSmoothingFF(OpBaseVigraFilter):
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/operators/vigraOperators.py", line 1521, in OpGaussianSmoothingFF
    vigraFilter =  staticmethod(fastfilters.gaussianSmoothing)
NameError: name 'fastfilters' is not defined

Original exception was:
Traceback (most recent call last):
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/shell/gui/startShellGui.py", line 91, in launchShell
    from ilastik.shell.gui.ilastikShell import IlastikShell
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/shell/gui/ilastikShell.py", line 45, in <module>
    from ilastik.widgets.ipcserver.zmqPubSubInfoWidget import ZMQPublisherInfoWidget
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/widgets/ipcserver/zmqPubSubInfoWidget.py", line 8, in <module>
    from ilastik.utility.ipcProtocol import Protocol
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/utility/__init__.py", line 24, in <module>
    from operatorSubView import OperatorSubView
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/ilastik/ilastik/utility/operatorSubView.py", line 21, in <module>
    from lazyflow.graph import OperatorWrapper, InputDict, OutputDict
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/__init__.py", line 32, in <module>
    import operators
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/operators/__init__.py", line 32, in <module>
    from vigraOperators import Op1ToMulti, Op5ToMulti, Op50ToMulti
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/operators/vigraOperators.py", line 1518, in <module>
    class OpGaussianSmoothingFF(OpBaseVigraFilter):
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/operators/vigraOperators.py", line 1521, in OpGaussianSmoothingFF
    vigraFilter =  staticmethod(fastfilters.gaussianSmoothing)
NameError: name 'fastfilters' is not defined

```

**Comment by svenpeter42** [comment]
uh oh, this is with fastfilters installed and a RGB jpg input image

```
ERROR 2016-07-28 14:28:18,949 excepthooks 31290 140530896115456 Traceback (most recent call last):
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/tiling.py", line 768, in _fetch_tile_layer
    img = ims_req.wait()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 158, in wait
    return self.toImage()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/pixelpipeline/imagesources.py", line 164, in toImage
    self._arrayreq.wait()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/pixelpipeline/slicesources.py", line 43, in wait
    return self._sp(self._ar.wait())
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 464, in wait
    rawData = self._rawRequest.wait()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 201, in wrapper
    return func(*args, **kwargs)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/volumina/volumina/pixelpipeline/datasources.py", line 225, in wait
    a = self._req.wait()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/operators/opReorderAxes.py", line 131, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/operators/generic.py", line 544, in execute
    self.Input(*input_roi).writeInto(result).wait()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/operators/opReorderAxes.py", line 131, in execute
    self.Input( *in_roi ).writeInto( result_input_view ).wait()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 480, in wait
    return self._wait(timeout)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 506, in _wait
    self._wait_within_request( current_request )
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 305, in _execute
    self._result = self.fn()
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/request/request.py", line 769, in __call__
    return self.func( *totalargs, **self.kwargs)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/slot.py", line 846, in __call__
    result_op = self.operator.execute(self.slot, (), self.roi, destination)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/slot.py", line 1538, in execute
    return self.operator.execute(self, totalIndex, roi, result)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/operators/vigraOperators.py", line 411, in execute
    return self.execute(self.Output, (), rroi, result)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/ilastik-meta/lazyflow/lazyflow/operators/vigraOperators.py", line 558, in execute
    buffer = fastfilters.gaussianSmoothing(sourceArrayV, tempSigma, window_size = self.WINDOW_SIZE )
  File "/home/speter/miniconda2/envs/ilastik-ff-test/lib/python2.7/site-packages/fastfilters/__init__.py", line 26, in func_wrapper
    res = func(squeezed, *args, **kwargs)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/lib/python2.7/site-packages/fastfilters/__init__.py", line 67, in gaussianSmoothing
    return __get_fn(array, core.gaussian2d, core.gaussian3d)(array, 0, sigma, window_size)
  File "/home/speter/miniconda2/envs/ilastik-ff-test/lib/python2.7/site-packages/fastfilters/__init__.py", line 47, in __get_fn
    "(Your image has {} channels.)".format(array.channels)
AssertionError: Can't handle multi-channel data. (Your image has 3 channels.)
```

**Comment by stuarteberg** [comment]
Can someone remind me what the status of this is?

@svenpeter42 @JaimeIvanCervantes

**Comment by JaimeIvanCervantes** [comment]
I thought that it was ready to merge, but now I have to test it on an env without fastfilters installed (hmm which is weird because I had checks for imports), and also on RGB images.

**Comment by stuarteberg** [comment]
Looks like the CI server is happy again after rebuilding the cache, so this is good to go as soon as you make that minor change we discussed.

**Pull request merged**
