### PR TITLE
Switch to travis

### PR DESCRIPTION
**Pull request by k-dominik**
With travis we can test on both, linux and macos for free these days.

Possible alternative would be azure devops services where one can test on all three major platforms

### CODE REVIEW

**Comment by k-dominik** [comment]
what do you guys think? is anyone rooting for microsoft? otherwise i'd add travis/remove circleci from the other repos as well

**Comment by emilmelnikov** [comment]
What about GitLab CI? They are very good at DevOps, and their runner tool is cross-platform, open-sourced and can be used in a self-hosted setting if needed. However, I am not sure if they have Windows and macOS instances in their SaaS.

**Comment by k-dominik** [comment]
@emilmelnikov is there a free version of the gitlab CI?

**Comment by emilmelnikov** [comment]
Yes, sure, they are free for open-source projects: https://about.gitlab.com/solutions/open-source/.

**Pull request merged**
