### PR TITLE
fixing some memory leaks in operators

### PR DESCRIPTION
**Pull request by burgerdev**
There were some problems with lingering `Operator`s, mostly caches.

### CODE REVIEW

**Comment by stuarteberg** [comment]
So, just to clarify: We'll know when this PR is ready by the removal of "WIP" from the title?

**Comment by burgerdev** [comment]
When I am done with all potential leaks I can think off, I will remove the WIP and tell you.

**Comment by burgerdev** [comment]
@stuarteberg ready to merge

**Comment by stuarteberg** [comment]
Love these changes, tests and all.  Thanks!

**Pull request merged**
